repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=6000']

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/psf/black
  rev: 22.8.0
  hooks:
  # Format Python files
  - id: black

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --preserve-quotes]

- repo: https://github.com/snakemake/snakefmt
  rev: 0.6.1
  hooks:
  - id: snakefmt